name: okejek_flutter
description: Okejek Android/iOS app

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 7.0.0+800000

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  animated_text_kit: ^4.2.1
  app_links: ^6.3.2
  bouncing_widget: ^2.0.0
  cached_network_image: ^3.1.0
  carousel_slider: ^5.0.0
  change_app_package_name: ^1.0.0
  contacts_service: ^0.6.3
  cupertino_icons: ^1.0.2
  dio: ^5.6.0
  double_back_to_close: ^2.0.0
  entry: ^1.0.0
  firebase_auth: ^5.2.1
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.3
  fl_toast: ^3.1.0
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.1
  flutter_local_notifications: ^17.2.3
  flutter_native_splash: ^2.4.2
  flutter_polyline_points: ^2.0.0
  flutter_speed_dial: ^7.0.0
  flutter_spinkit: ^5.1.0
  flutter_sticky_header: ^0.6.0
  flutter_svg: ^2.0.10+1
  flutter_swipe_action_cell: ^3.1.4
  flutter_tab_indicator_styler: ^2.0.0
  fluttertoast: ^8.0.8
  form_field_validator: ^1.1.0
  geocoding: ^3.0.0
  geolocator: ^11.1.0
  get: ^4.1.4
  google_maps_flutter: ^2.0.10
  google_sign_in: ^6.1.6
  http: ^1.1.0
  installed_apps: ^1.5.0
  intl: ^0.19.0
  loading_indicator: ^3.0.2
  modal_bottom_sheet: ^3.0.0
  package_info_plus: ^8.1.0
  permission_handler: ^11.0.1
  persistent_bottom_nav_bar: ^6.2.1
  shared_preferences: ^2.0.8
  shimmer: ^3.0.0
  sliding_sheet: ^0.5.0
  sliding_up_panel: ^2.0.0+1
  sticky_headers: ^0.3.0+2
  timeline_tile: ^2.0.0
  timelines: ^0.1.0
  top_snackbar_flutter: ^3.1.0
  uni_links: ^0.5.1
  url_launcher: ^6.0.12

dev_dependencies:

  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/ic_launcher.png"

flutter_native_splash:
  color: "#3c2782"
  image: assets/images/ic_launcher.png
  android: true
  ios: true
  # android_gravity: fill

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/ic_launcher.png"
  adaptive_icon_foreground: "assets/icons/ic_launcher.png"
  adaptive_icon_background: "#3C2782" # Atau warna background yang diinginkan
  min_sdk_android: 21

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/other/
    - assets/icons/ppob/
    - assets/icons/transparent/
    - assets/icons/white/
    - assets/icons/10-2021/
    - assets/icons/markers/
    - assets/images/icon_mart/
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-Light.ttf
          weight: 300
        - asset: fonts/Poppins-Bold.ttf
          weight: 600
